name: Synth_stats

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push: 
       branches: [main]
       paths:
            'designs/**'
  pull_request:
       branches: [main] 
       
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Update Submodules
        run: |
             git submodule update --init --recursive
             
      - name : Build dependencies
        run: |
             pip3 install pandas
             sudo apt install csvtool -y
             sudo apt install tcl-dev -y
    
             
      - name: Build Yosys
        run: |
             export PATH="$HOME/.local-bin/bin:$PATH"
             set -x
             if [ ! -e ~/.local-bin/bin/yosys ]; then
             echo '=========================='
             echo 'Building yosys'
             echo '=========================='
             mkdir -p ~/.local-bin
             cd yosys
             make config-gcc # Build Yosys using GCC
             PREFIX=$HOME/.local-bin make -j$(nproc)
             PREFIX=$HOME/.local-bin make install
             echo $(which yosys)
             echo $(which yosys-config)
             echo $(yosys-config --datdir)
             cd ..
             fi
             
             
      - name: Build Yosys-Plugins
        run: |
            cd yosys-symbiflow-plugins
            git checkout master
            export PATH="$HOME/.local-bin/bin:$PATH"
            make plugins
            make install
            cd ..
            
      - name: Synthesize all Benchmaarks on yosys
        run: |
             echo $(which yosys)
             make run_fpga_flow
            
      - name: Synthesize all Benchmaarks on yosys
        run: |
             export PATH="$HOME/.local-bin/bin:$PATH"
             make run_fpga_flow
             
      - name: Display contents
        run: |
             find -iname *.log
           
      - name: Generate and Display report
        run: |
             make csv_report
             csvtool -u comma readable ./Reports/designs_info.csv
