name: Synth_stats

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push: 
       branches: [main]
       paths:
            'designs/**'
  pull_request:
       branches: [main] 
       
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Update Submodules
        run: |
             git submodule init
             git submodule update
             
      - name: Build Yosys
        run: |
             sudo apt install tcl-dev -y
             set -x
             if [ ! -e ~/.local-bin/bin/yosys ]; then
             echo '=========================='
             echo 'Building yosys'
             echo '=========================='
             cd yosys
             make config-gcc # Build Yosys using GCC
             PREFIX=$HOME/.local-bin make -j$(nproc)
             PREFIX=$HOME/.local-bin make install
             echo $(which yosys)
             echo $(which yosys-config)
             echo $(yosys-config --datdir)
             cd ..
             fi
             
             
      - name: Build Yosys-Plugins
        run: |
            cd yosys-symbiflow-plugins
            git checkout master
            export PATH=$HOME/.local-bin:$PATH
            make
            make plugins
            make install
            cd ..
            
      - name: Synthesize all Benchmaarks on yosys
        run:
            sudo apt install tree -y
            tree
           
      - name: Generate and Display report
        run: |
             pip3 install pandas
             make csv_report
             sudo apt install csvtool -y
             csvtool -u comma readable ./Reports/designs_info.csv
